print("##########")
print("ASSASSINE-TXT-A")
print("##########")
print("materials symbols:")
print(" /\-_() ")
print("##########")
print(" ____  ")
print("/---/  ")
print("|---\  ")
print("\----| ")
print(" |---| ")
print("/----| ")
print("|____| ")
print("##########")
print("ASSASSINE-TXT-A-SWORD")
print("##########")
print("    /\ /\ ")
print("    || || ")
print("    || || ")
print("    || || ")
print("    /\ /\ ")
print("    \/ \/ ")
print("##########")
print("Ready printed")
print("##########")
print("data:")
print("##########")
print("----------")
print("Assassine(general):")
print("HP: 70")
print("without weapon:")
print("Damage: 25")
print("----------")
print("Sword:")
print("Damage: 2x 30")
print("----------")
input("Exit...")