print("##########")
print("BOW-TXT-A")
print("##########")
print("materials symbols:")
print(" /\-_() ")
print("##########")
print(" _____  ")
print(" \---o\ ")
print("  |--_| ")
print("  /---| ")
print(" |----| ")
print(" |____| ")
print("##########")
print("BOW-TXT-A-BOW")
print("##########")
print("    /\      ")
print("  /    \    ")
print(" /______|_> ")
print(" \      |   ")
print("  \    /    ")
print("    \/      ")
print("##########")
print("BOW-TXT-A-poison")
print("##########")
print("    __    ")
print("    ||    ")
print(" /------\ ")
print(" \------/ ")
print(" /------\ ")
print(" |------| ")
print(" \______/ ")
print("##########")
print("Ready printed")
print("##########")
print("data:")
print("##########")
print("----------")
print("Bow(general):")
print("HP: 70")
print("without weapon:")
print("Damage: 10")
print("----------")
print("Bow:")
print("Damage: 45")
print("----------")
print("Poison:")
print("Damage: 20 + effect")
input("Exit...")