import time
import os
clear = lambda: os.system('cls')
#Startet Programm
print("Willkommen zu Pyfight")
time.sleep(1)
clear()
#Einleitung
print("E")
time.sleep(0.1)
clear()
print("ES")
time.sleep(0.1)
clear()
print("ES W")
time.sleep(0.1)
clear()
print("ES WA")
time.sleep(0.1)
clear()
print("ES WAR")
time.sleep(0.1)
clear()
print("ES WAR E")
time.sleep(0.1)
clear()
print("ES WAR EI")
time.sleep(0.1)
clear()
print("ES WAR EIN")
time.sleep(0.1)
clear()
print("ES WAR EINM")
time.sleep(0.1)
clear()
print("ES WAR EINMA")
time.sleep(0.1)
clear()
print("ES WAR EINMAL")
time.sleep(0.1)
clear()
print("ES WAR EINMAL E")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EI")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EIN")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EIN K")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EIN KL")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLE")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLEI")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLEIN")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLEINE")
time.sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLEINER/S")
time.sleep(0.1)
name = input("Der Name lautet:")
clear()
print("ES WAR EINMAL EIN KLEINER/S" "Der Name lautet", name)
time.sleep(2)
clear()
print("Du musst deine ultimative Kraft auswählen.")
print("Dir stehen folgende zur Verfügung:")
print("(a) Feuer (Ein Feuerstrahl, der für 10 Sekunden lang pro Sekunde 5 Schaden verursacht)")
print("(b) Wasser (Ein Wasserstrahl, der 30 Schaden verursacht, senkt Angriffe von einer Gegnerischen Karte um 10 Schaden)")
print("(c) Gift (Ein Biss, wo jedes Mal, wenn der Gegner angegriffen hat, verliert seine Karte 10 Lebespunkte)")
ulti = input("Geben Sie (a), (b) oder (c) an:")
if ulti == ("a"):
    print("Deine Ultimative Kraft ist Feuer.")
if ulti == ("b"):
    print("Deine Ultimative Kraft ist Wasser.")
if ulti == ("c"):
    print("Deine Ultimative Kraft ist Gift.")
else:
    print("Da du keine Ultimative Kraft ausgewählt hast, musst du das Programm Neustarten.")
    time.seep(2)
time.sleep(0.5)
print("Danke für deine Daten.")
time.sleep(2)
clear()
print("Wir erstellen deine Visitenkarte.")
print("(Ultimative Kraft wird gespeichert)")
time.sleep(0.3)
clear()
print("Wir erstellen deine Visitenkarte.. ")
print("(Ultimative Kraft wird gespeichert)")
visitenkarteUlti = ("Ultimative Kraft:", ulti)
time.sleep(0.3)
clear()
print("Wir erstellen deine Visitenkarte... ")
print("(Geschlecht wurde gespeichert)")
time.sleep(0.3)
clear()
print("Wir erstellen deine Visitenkarte... ")
print("(Name wird gespeichert)")
visitenkarteName = ("Name:",  name)
time.sleep(0.3)
clear()
print("Wir erstellen deine Visitenkarte.")
print("(Visitenkarte wird gedruckt)")
visitenkarte = (visitenkarteName, visitenkarteGeschlecht)
time.sleep(0.3)
clear()
print("Visitenkarte erfolgreich erstellt.")
time.sleep(1)
print(visitenkarte)
print("Sie haben den Setup-Prozess erfolgreich absolviert.")
print("Jetzt müssen Sie die nächste Floppy-Disk einlegen. (0.2)")
print("ACHTUNG: Bevor Sie die nächste Floppy-Disk einlegen, müssen Sie noch einiges beachten:")
print("Gehen Sie in die Datei und nennen Sie name('user') zu Ihren Namen um. ")
print("Das Gleiche betrifft auch das Geschlecht. (Die Geschlechter sollen nur dazu dienen, damit die Dialoge besser als Comic dargestellt werden kann.)")
input("Drücken Sie 'ENTER', um das Programm zu schließen...")