import time
import os
clear = lambda: os.system('cls')
sleep = lambda: time.sleep()
#Startet Programm
print("Willkommen zu Pyfight")
sleep(1)
clear()
#Einleitung
print("E")
sleep(0.1)
clear()
print("ES")
sleep(0.1)
clear()
print("ES W")
sleep(0.1)
clear()
print("ES WA")
sleep(0.1)
clear()
print("ES WAR")
sleep(0.1)
clear()
print("ES WAR E")
sleep(0.1)
clear()
print("ES WAR EI")
sleep(0.1)
clear()
print("ES WAR EIN")
sleep(0.1)
clear()
print("ES WAR EINM")
sleep(0.1)
clear()
print("ES WAR EINMA")
sleep(0.1)
clear()
print("ES WAR EINMAL")
sleep(0.1)
clear()
print("ES WAR EINMAL E")
sleep(0.1)
clear()
print("ES WAR EINMAL EI")
sleep(0.1)
clear()
print("ES WAR EINMAL EIN")
sleep(0.1)
clear()
print("ES WAR EINMAL EIN K")
sleep(0.1)
clear()
print("ES WAR EINMAL EIN KL")
sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLE")
sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLEI")
sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLEIN")
sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLEINE")
sleep(0.1)
clear()
print("ES WAR EINMAL EIN KLEINER/S")
sleep(0.1)
geschlecht = input("(Mädchen/Junge) ACHTUNG: Bitte genauso eingeben.")
if geschlecht == ("Mädchen"):
    print("Bist du sicher?")
    sicher = input("Ja(J);Nein(N):(Programm muss neugestartet werden)")
    if sicher == ("N"):
        exit("Du bist nicht einverstanden")
if geschlecht == ("Junge"):
    print("Bist du sicher?")
    sicher = input("Ja(J);Nein(N):(Programm muss neugestartet werden)")
    if sicher == ("N"):
        exit("Du bist nicht einverstanden")
clear()
print("ES WAR EINMAL EIN KLEINER/S", geschlecht)
name = input("Der Name lautet:")
clear()
print("ES WAR EINMAL EIN KLEINER/S", geschlecht, "Der Name lautet", name)
sleep(0.5)
print("Danke für deine Daten.")
sleep(2)
clear()
print("Wir erstellen deine Visitenkarte.")
print("(Geschlecht wird gespeichert)")
sleep(0.3)
clear()
print("Wir erstellen deine Visitenkarte.. ")
print("(Geschlecht wird gespeichert)")
visitenkarteGeschlecht = ("Geschlecht:", geschlecht)
sleep(0.3)
clear()
print("Wir erstellen deine Visitenkarte... ")
print("(Geschlecht wurde gespeichert)")
sleep(0.3)
clear()
print("Wir erstellen deine Visitenkarte... ")
print("(Name wird gespeichert)")
visitenkarteName = ("Name:",  name)
sleep(0.3)
clear()
print("Wir erstellen deine Visitenkarte.")
print("(Visitenkarte wird gedruckt)")
visitenkarte = (visitenkarteName, visitenkarteGeschlecht)
sleep(0.3)
clear()
print("Visitenkarte erfolgreich erstellt.")
sleep(1)
print(visitenkarte)
