print("##########")
print("TANK-TXT-A")
print("##########")
print(" ()____()  ")
print("/--o--o--\ ")
print("\---__---/ ")
print("/--------\ ")
print("---------- ")
print("\-,,--,,-/ ")
print("##########")
print("TANK-TXT-A-SWORD")
print("##########")
print("    /\    ")
print("    ||    ")
print("    ||    ")
print(" <__--__> ")
print("    ||    ")
print("    ||    ")
print("    /\    ")
print("    \/    ")
print("##########")
print("TANK-TXT-A-SHIELD")
print("##########")
print("  ______  ")
print(" /------\ ")
print(" |--/\--| ")
print(" |--\/--| ")
print(" \------/ ")
print("  ------  ")
print("##########")
print("Ready printed")
print("##########")
print("data:")
print("##########")
print("----------")
print("Tank(general):")
print("HP: 100")
print("without weapon:")
print("Damage: 3")
print("----------")
print("Sword:")
print("Damage: 25")
print("----------")
print("Shield:")
print("HP: 50")
print("----------")
input("Exit...")