print("##########")
print("ASSASSINE-TXT-A")
print("##########")
print(" ____  ")
print("/---/  ")
print("|---\  ")
print("\----| ")
print(" |---| ")
print("/----| ")
print("|____| ")
print("##########")
print("ASSASSINE-TXT-A-SWORD")
print("##########")
print("    /\ /\ ")
print("    || || ")
print("    || || ")
print("    || || ")
print("    /\ /\ ")
print("    \/ \/ ")